# Environments sensitive for application
# Database Secrets
[default]
DATABASE_DIALECT_DRIVER="mysql+mysqlconnector"  # Example using dialect: "mysql+pymssql"
DATABASE_USER="root"
DATABASE_PASSWORD="root"
DATABASE_HOST="127.0.0.1"
DATABASE_PORT=3306
DATABASE_NAME="gym_movement"
