[default]
# Environments for default use in application
REST_APPLICATION_HOST="0.0.0.0"
REST_APPLICATION_PORT=8080
REST_APPLICATION_RELOAD=true
REST_APPLICATION_LOG_LEVEL="DEBUG"
REST_APPLICATION_NAME="Gym Movement"
REST_APPLICATION_DESCRIPTION="Gym Movement Application"
REST_APPLICATION_WORKERS=3